name: empty_fridge_shopping_list_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^3.4.6
  connectivity_plus: ^2.3.6+1
  firebase_core: ^1.21.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  intl: ^0.17.0
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.1.0
  equatable: ^2.0.5
  firebase_auth: ^3.9.0
  flow_builder: ^0.0.9
  flutter_test:
    sdk: flutter
  formz: ^0.4.1
  hydrated_bloc: ^8.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
